name: HelloFunction CICD
on:
  pull_request:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master          # triggers on pushes that contain changes in master

env:
  AZURE_WEBAPP_NAME: HelloActions    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to AzureFunction App.
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.3.2
      with:
        # Name of the Azure Function App
        app-name: HelloActions
        # Path to package or folder. *.zip or a folder to deploy
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        # Publish profile (*.publishsettings) file contents with web deploy secrets
        publish-profile: ${{secrets.PUBLISH_PROFILE}}
        # Remove unwanted files defined in .funcignore file (default: 'false'). When this is set to 'true', 'package' should point to the folder of host.json.
        respect-funcignore: true

